### ISSUE TITLE
Where is the firmware?

### ISSUE THREAD

**Issue by matthew-lawrence** [tevo3d/Tevo-Nereus#1]
The links here don't work or go to the right place and it is not on the website. The Auto leveling version does not come with the correct firmware. You show the files here https://www.youtube.com/watch?v=dzmj4GHupAE but there is nowhere to download them. Please, I don't want to return the Nereus to Amazon, but it is a free return if the product does not work, and the autoleveling does not work without the right firmware apparently.

**Comment by Homers3D** [comment]
Can you send me an email   alex@tlmaker.com
I will send you by mail. also I will complete it on our web and GitHub.

**Comment by matthew-lawrence** [comment]
This autolevel firware does not work. After installing and homing it messes up the axis.
